export const GroceryItems: string[] = [
  "milk",
  "whole milk",
  "skim milk",
  "eggs",
  "egg",
  "butter",
  "buttr",
  "cheese",
  "cheddar",
  "ched chz",
  "yogurt",
  "yoghurt",
  "bread",
  "white bread",
  "wheat bread",
  "loaf",
  "chicken",
  "chicken breast",
  "chick",
  "chkn brst",
  "ground beef",
  "grnd beef",
  "hamburger",
  "salmon",
  "salmon fillet",
  "bacon",
  "rice",
  "white rice",
  "brown rice",
  "pasta",
  "spaghetti",
  "macaroni",
  "olive oil",
  "oliveoil",
  "oil",
  "canned tomatoes",
  "tomato sauce",
  "tomato",
  "black beans",
  "beans",
  "lentils",
  "potatoes",
  "potato",
  "onions",
  "onion",
  "garlic",
  "bell peppers",
  "pepper",
  "mushrooms",
  "spinach",
  "broccoli",
  "carrots",
  "apples",
  "apple",
  "bananas",
  "banana",
  "oranges",
  "orange",
  "peanut butter",
  "pb",
  "cereal",
  "coffee",
  "ground coffee",
  "coffee beans",
  "grape",
  "grapes",
];

export const NonFoodItems: string[] = [
  "savings",
  "toilet paper",
  "toilet tissue",
  "bath tissue",
  "tp",
  "paper towels",
  "paper towel",
  "ptowel",
  "facial tissues",
  "tissues",
  "napkins",
  "aluminum foil",
  "foil",
  "plastic wrap",
  "cling wrap",
  "saran wrap",
  "parchment paper",
  "trash bags",
  "garbage bags",
  "dish soap",
  "dishwashing liquid",
  "dish liquid",
  "sponges",
  "sponge",
  "dish scrubbers",
  "scrubber",
  "all-purpose cleaner",
  "cleaner",
  "disinfectant wipes",
  "disinfecting wipes",
  "wipes",
  "glass cleaner",
  "window cleaner",
  "bathroom cleaner",
  "bath cleaner",
  "laundry detergent",
  "detergent",
  "laundry soap",
  "fabric softener",
  "softener",
  "dryer sheets",
  "hand soap",
  "soap",
  "hand sanitizer",
  "sanitizer",
  "shampoo",
  "conditioner",
  "body wash",
  "bar soap",
  "toothpaste",
  "toothbrush",
  "toothbrushes",
  "dental floss",
  "deodorant",
  "razors",
  "shaving cream",
  "feminine hygiene products",
  "feminine products",
  "diapers",
  "baby wipes",
  "batteries",
  "battery",
  "light bulbs",
  "light bulb",
  "bulbs",
  "candles",
  "matches",
  "air fresheners",
  "air freshener",
  "greeting cards",
  "aluminum pans",
  "foil pans",
  "plastic food storage bags",
  "storage bags",
  "zip bags",
  "ziploc",
];

export const InglesReceipt: string[] = [
  "GROCERY",
  "2 @ 1.28",
  "A   R.w.CR.MUSHRM   1.98 B",
  "B  LLALUMINUMFOIL   1.98 T",
  "SC 8900 A  ADV SAVINGS     1.00",
  "PRODUCE",
  "4 @ 4/1.00",
  "A  LL SPRING WATE  2.56 B",
  "A  ADOBO W/PEPPER  1.98 B",
  "A  ARIZONAGREENTEPC  2.98 B",
  "3 @ 0.68",
  "A  LL. JUMBO EGGS 2.98 B",
  "A  BORDENLACTOSEPC  2.48 B",
  "A  PEPPERS  1.00 B",
  "A  GARLIC 2.04 B",
  "A  RED GRAPE TO  2.98 B",
  "DELI",
  "B  SANTE FE CHICK  6.98 B",
];

export const FoodLionReceipt: string[] = [
  "DELI",
  "TOI ALL NTL CRIG HMM M 3.49 A *",
  "GROCERY",
  "BUSH BEST BLACK BEAN 2.49 A *",
  "GOYA BLK BNS 29Z   3..39 A *",
  "GROCERY",
  "NP DRUMSTICKS  M 5.05 A *",
  "PRODUCE",
  "MEDIUM NACEK ORANGES W",
  "   3 @ 0.89  2.67 A *",
  "POMEGRANATES   WM",
  "1 @ 2 FOR  4.58  2.29 A *",
  "BANANAS    W",
  "HASS AVOCADOS    W",
  "GREEN CUCUMBERS    WM",
  "SWEET CORN   W",
  "YELLOW ONIONS  W",
  "CRIPPS PNK LADY APLS W",
  "BROCOLI CROWNS W",
  "RED TOMATOES ON VINE W",
  "SUSNET ANGEL SWT GRP",
];
export default GroceryItems;
